### ISSUE TITLE
Suggestion to add more details to ticket table

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2018#107]
As I was going through the tickets table, the most common question that I had in mind was what the ticket would include. And I am sure everyone does. I think we should add more details that are confirmed under the tickets table so people could understand the value. 
- Maybe add a link to Convince My Boss there. I am still not sure where it should be added. I think this place would be the most appropriate.
- Or the blog link of ticket sales could be added underneath it. (Refer https://github.com/pythonindia/inpycon-blog/pull/144)

**Comment by ananyo2012** [comment]
On Thu, May 31, 2018 at 12:39 PM Vipul Gupta <notifications@github.com>
wrote:

>
>    - As I was going through the tickets table, the most common question
>    that I had in mind was what the ticket would include. I think we should add
>    more details that are confirmed under the tickets table so people could
>    understand the word of it.
>
> It has the information for the days of entry. There is a FAQ regarding
what a conference/workshop ticket would include. Do we need to add it here
?

>
>    - Maybe add a link to Convice My Boss there. I am still not sure where
>    it should be added. I think this place would be the most appropriate
>
> Uh I am still not sure as well. Perhaps we can add the link at the end of
the table ?

**Comment by vipulgupta2048** [comment]
It's just a suggestion, I was thinking to maybe add the blog link below the **table** (The Price Table of tickets here - www.in.pycon.org/#tickets)

**Comment by vipulgupta2048** [comment]
Should I add it?

**Comment by ananyo2012** [comment]
Ah I guess we have included all the information the blog contains in the table already. But adding convince the link to convince my Boss is fine.

**Comment by vipulgupta2048** [comment]
Cool, I have added the link in my PR. Thanks for your consideration.
