### ISSUE TITLE
Fix google map co-ordinates

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/inpycon2018#11]
Presently Google map is pointing to london. We need it to point to BIEC

https://www.google.co.in/maps/place/Bengaluru+International+Exhibition+Centre/@13.0622611,77.4719009,17z/data=!3m1!4b1!4m5!3m4!1s0x3bae235720cf15b9:0x10b800c631021f0e!8m2!3d13.0622611!4d77.4740896

**Comment by webchirpy** [comment]
Added new co-ordinates.
