### ISSUE TITLE
Create a dedicated page for all speakers

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#111]
Since all speakers are working hard to write their proposals and present them, it is worth making a page for all speakers with their image and bio and link their proposals to it. CFP team will collect the images and bio for us after proposal selection in over.

**Comment by vipulgupta2048** [comment]
After Keynote speaker images, how about a button "Show more" that takes the user to another page having all the speakers

**Comment by a2un** [comment]
Taking this up!

**Comment by a2un** [comment]
Hi could you confirm if the issue is open

**Comment by ananyo2012** [comment]
Yup this issue is open. You can take this up.

**Comment by ananyo2012** [comment]
Vipul, this is not the same as the CFP page. It will contain the Speakers
image, bio and links, somewhat more attractive and showcasing the speakers.
It will also link to the CFP page.

**Comment by a2un** [comment]
So is the idea  to introduce a show more button or make a separate page that lists all the speakers with details

**Comment by ananyo2012** [comment]
@a2un Make a separate page.

**Comment by vaibhavsingh97** [comment]
@vipulgupta2048 We can make on `.json` file and then populate it on the website. Views?

**Comment by ananyo2012** [comment]
@vaibhavsingh97 Yup that's the idea. Mock design of the page is welcome

**Comment by vaibhavsingh97** [comment]
@ananyo2012 Should I send PR?

**Comment by vipulgupta2048** [comment]
@vaibhavsingh97 Shoot one up, no need to ask for permission. 
@thisisayush Where is the scraper script for proposals can you send a link. @vaibhavsingh97 can test it out.

**Comment by ananyo2012** [comment]
@vipulgupta2048  @thisisayush Here is a script that scrapes some basic elements https://github.com/surajnarwade/pycon-india-scripts/blob/master/voting_script/pyconspider.py . You can add to this as well

**Comment by ananyo2012** [comment]
@vaibhavsingh97 Any update on this ?

**Comment by vaibhavsingh97** [comment]
@ananyo2012 Sent PR https://github.com/pythonindia/inpycon2018/pull/141
