### ISSUE TITLE
Update the content of share bar ribbon to promote ticket Sales

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#115]
We want users who come in the website to promote about ticket sales from the share bar ribbon directly. We need to update content as per that.

**Comment by realslimshanky** [comment]
Any suggested write-up contributors should use in their PR?

**Comment by ananyo2012** [comment]
Yeah can you tag someone you know who is good in writing or forward him/her
the PR ?

**Comment by realslimshanky** [comment]
@ananyo2012 sure. I'll reach out to folks with this issue.

**Comment by manjeet-mehta** [comment]
I want to help with that what I can do ? #newbie 😅

**Comment by realslimshanky** [comment]
@manjeet-mehta thanks for the interest. You can start by creating messages for the ribbon and posting it here.

**Comment by manjeet-mehta** [comment]
like "Mark the date October 5th for the biggest conference of python in india and celebrate with us the 10th anniversary of @pyconindia"

**Comment by ananyo2012** [comment]
We should have something related to promote ticket sales. Like "buy your ticket now"

**Comment by vipulgupta2048** [comment]
I am taking this up, getting it done and closing it.

**Comment by vipulgupta2048** [comment]
`Mark your calendars and buy your tickets for the 10th edition of India's biggest Python conference, PyCon India 2018. A 5-day mega event filled with awesome keynotes, talks, seminars, sprints, and workshops. Get your tickets now !!`

Review @ananyo2012 @realslimshanky @iambibhas (Well, within twitter limit)

**Comment by ananyo2012** [comment]
Sounds good to me. Just remove one exclamation mark at the end.
