### ISSUE TITLE
Fix the border for keynote speakers

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#116]
Here is the screenshot presently
![screenshot from 2018-06-03 20-16-28](https://user-images.githubusercontent.com/10486343/40887768-07050384-676b-11e8-8edf-f42210e30a10.png)

The alignment of the border doesn't look good for all images. So let us just keep it simple and put the border around the image instead of shifting it.

**Comment by realslimshanky** [comment]
@ananyo2012 someone might also try putting a background behind Travis's picture to see if it makes it even.

**Comment by callowidealist** [comment]
@realslimshanky i think grey might look much attractive than black .

**Comment by vipulgupta2048** [comment]
Would it affect the animation that @thisisayush is working on for Speaker Description. 
Ps. I think the borders are all right.

**Comment by ananyo2012** [comment]
I got some comments offline that the border alignment was not looking good
specially those over Travis's image. So I think its good to have properly
aligned borders.

**Comment by eddygta17** [comment]
Did the following and posting the results.
Made the border simple.
![screenshot from 2018-06-07 13-46-19](https://user-images.githubusercontent.com/24777071/41088910-4b8fe546-6a5e-11e8-9b7a-d2798bcffb2e.png)

Changed Travis's picture and border.
![screenshot from 2018-06-07 13-57-38](https://user-images.githubusercontent.com/24777071/41088913-4be1ee7c-6a5e-11e8-8c8f-b54898a39c1b.png)

Changed just Travis's picture.
![screenshot from 2018-06-07 13-58-55](https://user-images.githubusercontent.com/24777071/41088914-4c1e2784-6a5e-11e8-8ee7-b16c9ed60e1f.png)

Used black and white images for all speakers.
![screenshot from 2018-06-07 14-30-41](https://user-images.githubusercontent.com/24777071/41089502-92d20366-6a5f-11e8-882f-73012530cde3.png)

**Comment by omi10859** [comment]
![screen shot 2018-06-08 at 10 25 25 am](https://user-images.githubusercontent.com/26123416/41139630-73f943da-6b06-11e8-9c1f-7dd7e0bb5373.png)

It's not responsive when opening from different screens we get different results of the border 
this is what I got when opened in iPad

**Comment by eddygta17** [comment]
@omi10859 That is because position is fixed as absolute. We can try to keep the same design everywhere.

**Comment by ananyo2012** [comment]
@eddygta17 I like [this version](https://user-images.githubusercontent.com/24777071/41088910-4b8fe546-6a5e-11e8-9b7a-d2798bcffb2e.png) . Don't use a different image of the speaker whatsoever. The image is given to us by the speaker himself. The border is breaking in one of the screen width. We need to fix that as well.

**Comment by thisisayush** [comment]
@omi10859 The absolute position bug has been fixed in #97

**Comment by ananyo2012** [comment]
I actually want to wait on #97 before proceeding on this issue since it introduces a lot of css changes and also takes care of issues like the one @omi10859 mentioned and padding in medium screen width. So after it has been merged we can move on this.

**Comment by ananyo2012** [comment]
Fixed in #120
