### ISSUE TITLE
Text in speaker description

### ISSUE THREAD

**Issue by eddygta17** [pythonindia/inpycon2018#121]
Text in speaker description would be better if centered.

**Comment by vipulgupta2048** [comment]
Thanks for the prompt response @eddygta17, the changes can be done in your PR #120 only. 
@ananyo2012 I think the text should be centered, in both the website and mobile if the changes in #120 are approved. What do you think ?

**Comment by ananyo2012** [comment]
Yeah centered text looks better. We should center all keynote speaker texts.

**Comment by ananyo2012** [comment]
Fixed in #120
