### ISSUE TITLE
Navigation Bar on Convince My Boss page

### ISSUE THREAD

**Issue by atisayajain** [pythonindia/inpycon2018#122]
Hi, I have observed that the navigation bar's properties don't change on scrolling on Convince My Boss page like the rest of the site. I am attaching a screenshot regarding the issue.

![screen shot 2018-06-10 at 2 14 43 pm](https://user-images.githubusercontent.com/19758073/41199933-d2e8f256-6cb8-11e8-824a-340a757b7c02.png)

It's a pretty easy fix and all that needs to be done is add links to JS files related to scrolling. I can make the PR as soon as I receive confirmation.

**Comment by aaqaishtyaq** [comment]
hey @atisayajain are you working on this?

**Comment by atisayajain** [comment]
@vipulgupta2048 Sure, I will add the PyCon India logo as well. Also, I have observed that there is no favicon icon for this page so I am adding links for that as well.

@aaqaishtyaq Yeah, I am working on this.

**Comment by ananyo2012** [comment]
Fixed in #125
