### ISSUE TITLE
Add download buttons to Convince My Boss

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2018#130]
@rajataaron suggested we should add download buttons for Convince my Boss page where users could easily download the text in .docx or plain-text format. 

Hence this has been implemented in the PR #119

**Comment by ananyo2012** [comment]
Can we use a copy to clipboard button instead of that?

**Comment by vipulgupta2048** [comment]
We could but I thought having them is much better bet. People can edit the .docx in whatever way they want and use it. And anyone, in any device could easily copy the content. The reason why I didn't go for a copy to clipboard feature because of embedded links. We don't want to miss out on them.

**Comment by vipulgupta2048** [comment]
About the buttons, how would you like them?

**Comment by ananyo2012** [comment]
Can we use fontawesone icons instead? They look much better. Let me find
some good icons that can be used here.

**Comment by vipulgupta2048** [comment]
@ananyo2012 Any updates?

**Comment by ananyo2012** [comment]
I was travelling today. Couldn't get time to look. In the mean time if you find any good icons please use them.

**Comment by vipulgupta2048** [comment]
I got some like https://fontawesome.com/icons/download?style=solid, should I proceed?

**Comment by darthgera123** [comment]
can i work on this issue. Basically i have to create a button which downloads the application in word form right?

**Comment by ananyo2012** [comment]
This is already fixed in #137
