### ISSUE TITLE
PyCon logo conflicts with current theme colour in mobile menubar

### ISSUE THREAD

**Issue by dhavalsavalia** [pythonindia/inpycon2018#135]
PyCon logo has the same colour accents as of menubar background in mobile view.

Here is screenshot:

![screen shot 2018-06-13 at 7 17 37 pm](https://user-images.githubusercontent.com/27001046/41355536-6535c8a4-6f3f-11e8-8c0e-dc9773a0a7fd.png)

Suggestion:

![screen shot 2018-06-13 at 6 50 40 pm](https://user-images.githubusercontent.com/27001046/41355561-72a48318-6f3f-11e8-9f91-b8de3bac3e84.png)

White background recommended with theme coloured menubar toggle.

**Comment by ananyo2012** [comment]
Yes please go ahead and fix this. This has to be done for all pages. Also use white background in navbar similar to blog.

**Comment by rajataaron** [comment]
@dhavalsavalia this looks good to be please go ahead with the PR @ananyo2012

**Comment by dhavalsavalia** [comment]
Yes, I have already fix the issue. Once everything is ready I'll push the code and create PR.

**Comment by realslimshanky** [comment]
@dhavalsavalia any update on the upcoming PR?

**Comment by ananyo2012** [comment]
@dhavalsavalia I guess you are confused with the description of the bug you filed. This is only for fixing the logo color in mobile navbar. No change in links is required. Also this has to be done in all pages, which is an independent change from #134. Please go ahead and make a PR for the same.

**Comment by ananyo2012** [comment]
@dhavalsavalia Now that #134 is merged can you do the same changes in navbar for other pages as well ?

**Comment by dhavalsavalia** [comment]
@ananyo2012 I have fixed the same issue in all other pages.
