### ISSUE TITLE
Ticket Pricetable is not mobile responsive

### ISSUE THREAD

**Issue by tulikavijay** [pythonindia/inpycon2018#138]
Not sure if someone has fixed this. Found the website and this section was lacking in responsiveness.

**Comment by realslimshanky** [comment]
@tulikavijay thank you for the mentioning this issue. As of now, the approach is to use a table with scrollable content which can be seen below and you might have experienced the same.
![image](https://user-images.githubusercontent.com/10004530/41745751-ab4aee0a-75c5-11e8-8e72-bb8f3bd8e950.png)

If you are facing another issue please upload a screenshot to make us understand the issue accurately. Or if you are also experiencing the above behavior of table, could you please share a better alternative?

**Comment by 2root2** [comment]
@ananyo2012  Can I work on this? If I get it right, I'll replace table with bootstrap's col-md-6-3-3 for big screens and col-xs-12 for mobile device.

**Comment by ananyo2012** [comment]
@2root2 Yes you have to use bootstrap grids. You can take this up.

**Comment by 2root2** [comment]
@ananyo2012  Please review #142

**Comment by ananyo2012** [comment]
Nice work @2root2 . Merged and deployed!
