### ISSUE TITLE
Organise navbar in website - Introduce a More dropdown

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#149]
The no of links in the navbar is increasing now. Let's make a More button and move the less visited content in that. Create a More dropdown and add Volunteer, CoC and Proposals link in that dropdown.

**Comment by Rohithgilla12** [comment]
I'll take it up

**Comment by Rohithgilla12** [comment]
<img width="977" alt="screenshot 2018-07-17 08 44 51" src="https://user-images.githubusercontent.com/19389850/42794661-b26a6b48-899d-11e8-8463-6570742c5c43.png">

We don't have proposal tab over there currently, should i add one now?
