### ISSUE TITLE
Add sponsors to the website 

### ISSUE THREAD

**Issue by chirag200666** [pythonindia/inpycon2018#151]
Platinum 
------------

- [x] **Go-Jek**
Description: https://docs.google.com/document/d/1bKBVfsFyLuB0C2pl71dO24RmyiUS6jNjIQ-ZdTxrGiw/
Logo: https://drive.google.com/file/d/1HXn-U_bBK0K2U4W7pt9TAHBDLtdGokea/

- [x] **DE Shaw**
Description: Sent in email
Logo: Sent in email

Gold
-------

- [x] **Pramati Technologies**
Description: https://docs.google.com/document/d/1Rre9s5cfoD5CxFiHUXOXgsMHGmUG7cO21_vNjFKZTVU/
Logo: https://drive.google.com/file/d/1arIO23d0mDo3UJJcZjTNTjICtl_XplMW/

- [x] **LiveHealth**
Description: https://docs.google.com/document/d/19_fPSH0qqiRIVaTklflGLZm_WyDnffx2rSgrYzIEmo8/ 
Logo: https://drive.google.com/file/d/1_GIafdoAD5PFwaWCBX9cqa8GuAIROsxU/

Silver
--------

- [x] FOSSEE
Details: https://docs.google.com/document/d/1YzVMyZnxIkhbd6Zpg1MeNnoUSjX0WoW6M9vOgagWDz0/edit?usp=sharing

- [x] IBM : https://github.com/pythonindia/inpycon2018/issues/151#issuecomment-422809710

**Comment by im-gozmit** [comment]
I want to work on this.

**Comment by vipulgupta2048** [comment]
Go ahead, Mayank make a PR referring to this issue.

**Comment by realslimshanky** [comment]
@im-gozmit nice work Mayank. Would you like to work on the LiveHealth and GoJek issue as well?

**Comment by im-gozmit** [comment]
@realslimshanky Thanks, and I am already working on Go-Jek and LiveHealth. Just pushed the PR for go-jek https://github.com/pythonindia/inpycon2018/pull/

**Comment by ananyo2012** [comment]
Testing webhook

**Comment by vipulgupta2048** [comment]
FOSSEE logo added in #159 and blog in https://github.com/pythonindia/inpycon-blog/pull/167
DeShaw's blog has already been added. I think this issue is done.

**Comment by ananyo2012** [comment]
Let this be open for sometime. We have more sponsors coming in. We can add them to the same issue.

**Comment by chirag200666** [comment]
IBM India
IBM has been present in India since 1951. Since inception, IBM India has expanded its operations with regional headquarters in Bangalore and offices in over 20 cities. These include regional offices in New Delhi, Mumbai, Kolkata and Chennai. Today, IBM India has established itself as one of the leaders in the Indian Information Technology Industry. 

As a leading cognitive solutions and cloud platform company, innovation is at the core of the IBM company strategy. This is reflected in the end-to-end solutions delivered to clients, which span from software and systems hardware to a broad range of infrastructure, cognitive, cloud and consulting services.

IBM helps clients solve complex business and technical issues by delivering deep business process and industry expertise. This is enhanced with advanced analytics, research capabilities, comprehensive IT infrastructure knowledge and the proven ability to implement enterprise solutions to deliver bottom line value to businesses and governments worldwide. 

For more information on IBM India log on to: www.ibm.com/in
For information on IBM Corporate visit : https://www.ibm.com/annualreport/


https://www.ibm.com/innovate/branding/logoartwork/logoartwork.nsf/vwArtworkFiles/949604AC5FDBC72986258305002A7D76?OpenDocument
@ananyo2012

**Comment by realslimshanky** [comment]
@chirag200666 Please also mention the type of sponsorship for more help to @ananyo2012.

**Comment by chirag200666** [comment]
ZeOmega : Silver

ZeOmega is the premier enabler of value-based care. We provide technical solutions to facilitate collaboration among healthcare stakeholders. Jiva™, our Population Health Management Solution, helps healthcare organizations achieve Triple Aim goals. 

Website:
http://www.zeomega.com/

logo:
http://www.zeomega.com/wp-content/uploads/WEB-235-ZeOmega-Logo.png

**Comment by rahulkumaran** [comment]
Is this already done or assigned to anyone? If not, then I'd like to take it up

**Comment by ananyo2012** [comment]
Please go ahead. I think we are not writing blogs for Silver Sponsor. So
just add the logo to the website. Also please try to keep the image size
less than 50kb. You can use imagemagick for compression

**Comment by realslimshanky** [comment]
@rahulkumaran please checkout review on your pull request.

**Comment by ananyo2012** [comment]
Closing this and moving issues to blog repo
