### ISSUE TITLE
Make Conference Schedule responsive 

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#162]
Go to https://pythonindia.github.io/inpycon2018/#conference, the conference schedule is not responsive for mobile views. It is currently made of table. We need to use bootstrap grids to make it responsive. On master you need to apply changes in this commit https://github.com/pythonindia/inpycon2018/commit/e28c63cbba381079cbbd87b7b227b2d85570628d to be able to see the schedule. It's currently commented out in master now.

**Comment by 2root2** [comment]
@ananyo2012 Can I take this up?

**Comment by ananyo2012** [comment]
Yes please go Ahead. We need this immediately. Can you finish it in next
couple of days?

**Comment by 2root2** [comment]
@ananyo2012 We have some problem with layout, All Hall Numbers stack-up on top and then schedule is displayed, Have a look at my [gh-pages](https://2root2.github.io/inpycon2018/) in mobile view. Currently I've done for Day-1. Please suggest some alternative so as to display Hall Numbers against the schedule. Thanks.

**Comment by ananyo2012** [comment]
There are some more issues presently. The dates don't shoe properly in the mobile view. They get cut off from the table and are not visible properly. Please fix that.

Also please use a `col-md` for each tack item so that they also show side-by-side in medium grid view. Let's see how it looks. If that doesn't look good we can continue using the same.
