### ISSUE TITLE
Improve Website load performance

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#163]
For starting we need to work on following

- [x] Make sponsor images compressed and of similar dimensions
- [x] Compress any jpeg images that can be done retaining the image visibility. Preferably make them png
- [ ] Use caching for json data. Currently we are using `sponsors.json` to load data for sponsors. We need to cache the data on first load so that on subsequent loads the website loads faster

**Comment by vipulgupta2048** [comment]
@parthsharma2 would you like to take it up, since you previously worked on the same objective?

**Comment by ananyo2012** [comment]
@bhansa Yes please go ahead.

**Comment by vipulgupta2048** [comment]
@bhansa Can you also cover caching of JSON data in your current PR, this would completely fix this issue,

**Comment by bhansa** [comment]
@vipulgupta2048  @ananyo2012 please review the last(caching JSON data) requirement as well.

**Comment by ananyo2012** [comment]
@bhansa Any update on the caching improvement. We talked on applying a timeout for the cache.

**Comment by vipulgupta2048** [comment]
@ananyo2012 @bhansa @realslimshanky we can get more reach by adding these labels in our issues. Since Hacktoberfest has started. People could possibly suggest new ways to improve performance.

**Comment by ananyo2012** [comment]
Yeah that's a good idea. Let's do that.

**Comment by fenilgandhi** [comment]
0.001 ETH on gitcoin ssly. Don't you think that's a little too high (Sarcasm intended). Anyone would have done it for free just knowing that it is open-source contribution(not me).

**Comment by vipulgupta2048** [comment]
Hi @fenilgandhi, can you provide the link to the Gitcoin advert that redirected you here. Thanks.

**Comment by fenilgandhi** [comment]
Here you go 
```https://gitcoin.co/issue/pythonindia/inpycon2018/163/1466```
