### ISSUE TITLE
Broken CSS in safari

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/inpycon2018#17]
https://in.pycon.org/2018/
![screen shot 2017-12-29 at 8 27 04 am](https://user-images.githubusercontent.com/316253/34428376-3d263efc-ec72-11e7-9d70-e09a4567ef3f.png)

**Comment by webchirpy** [comment]
Looks like a cache issue, We too experienced the same and after clearing the cache everything is set.

**Comment by vnbang2003** [comment]
Yep closing it
