### ISSUE TITLE
Fixing the sponsor section UI

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2018#175]
The sponsor logos which are of different sizes are currently not aligned properly and hence doesn't look good. A minor fix is needed to resolve this issue.

**Comment by rajataaron** [comment]
@realslimshanky is the issue solved? If not then let me know once.

**Comment by ananyo2012** [comment]
There is a PR #176 for this. I made some comments there. Once that is done I can merge it.

**Comment by realslimshanky** [comment]
@rajataaron I've tried solving the issue with #176, please review.
