### ISSUE TITLE
Feeds for latest update section

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/inpycon2018#18]
Feeds for latest update section

twitter link : https://twitter.com/pyconindia
blog link : http://in.pycon.org/blog/2018/

**Comment by webchirpy** [comment]
Updated!

**Comment by vnbang2003** [comment]
Can you just restrict blog feed to : http://in.pycon.org/blog/2018/
right now I see we are even getting older blog : http://in.pycon.org/blog/2017/

**Comment by webchirpy** [comment]
Updated to show only 2018!

**Comment by vnbang2003** [comment]
Thanks . Closing it
