### ISSUE TITLE
FAQ: Related to workshop.

### ISSUE THREAD

**Issue by rajataaron** [pythonindia/inpycon2018#180]
We should add some questions related to workshop to the FAQ section like:
1) I have brought the ticket for morning workshop but I want to attend evening workshop can I do that?
2) I have brought the workshop ticket am I eligible to participate in DevSprint?
3) Can I switch between the workshop in session time?

**Comment by ananyo2012** [comment]
Ok I will add them to the FAQ

**Comment by ananyo2012** [comment]
Added to the Website. Closing this.
