### ISSUE TITLE
Spelling error in index

### ISSUE THREAD

**Issue by uzerjamal** [pythonindia/inpycon2018#188]
On line 276 in index.html 'frequent' is spelled as 'frequesnt'

**Comment by uzerjamal** [comment]
#189

**Comment by uzerjamal** [comment]
#189

**Comment by uzerjamal** [comment]
#189

**Comment by uzerjamal** [comment]
#189

**Comment by realslimshanky** [comment]
@uzerjamal Ideally the issue should be closed automatically with a merged pull request.

**Comment by realslimshanky** [comment]
@uzerjamal are you facing any trouble? What's up with multiple pull requests? #190 #195?

**Comment by uzerjamal** [comment]
Sorry i'm a beginner and didn't know how to "update" a pull request with more changes so i just closed the old request #189 and made a new one #195 .
#190 is some other guy who guy who made the pull request after me. At that time i didn't know i had to reference it here and close it so i did it when i found out
