### ISSUE TITLE
Fix blog link in the navbar

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2018#19]
The "Blog" tab points to a wrong link. Need to point it to the correct one.

**Comment by webchirpy** [comment]
Fixed!

**Comment by SaptakS** [comment]
You seem to have added the blog link only on the index.html page and missed the coc.html and faq.html according to the code pushed in your last commit. Can you please check and verify?

**Comment by webchirpy** [comment]
Added appropriate link to all HTML pages.

**Comment by SaptakS** [comment]
Fixed. Closing.
