### ISSUE TITLE
the pycon india logo is not aligned whenever screen size is reduced

### ISSUE THREAD

**Issue by steve7158** [pythonindia/inpycon2018#191]
![pyconissue](https://user-images.githubusercontent.com/40897792/45585061-cec32e00-b8fb-11e8-959f-fcfb06a7ecf2.PNG)

**Comment by ananyo2012** [comment]
@steve7158 Also can you do a hard reload to confirm if this isn't a caching issue ?

**Comment by steve7158** [comment]
The problem seems to be occuring in pythonindia.github.io and not in https://in.pycon.org/2018/

**Comment by ananyo2012** [comment]
Oh don't worry about that. The gh-pages branch hasn't been updated for
quite some time since we have been using netlify for code reviews now

**Comment by realslimshanky** [comment]
I guess we can close this issue not since it doesn't give out errors to our production server.
