### ISSUE TITLE
wrong button is highlighted in navigation bar

### ISSUE THREAD

**Issue by steve7158** [pythonindia/inpycon2018#192]
home is getting highlighted when in blog 
![inpycon issue 2](https://user-images.githubusercontent.com/40897792/45585153-80169380-b8fd-11e8-9b20-4f9aedf2c2a3.PNG)

**Comment by realslimshanky** [comment]
@steve7158 this issue doesn't belong to this repository. It belongs to [pythonindia/blog](https://github.com/pythonindia/inpycon-blog) and has already been handled by https://github.com/pythonindia/inpycon-blog/issues/174
Thank you for raising the issue.
