### ISSUE TITLE
Speakers images are not loading

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2018#196]
Speakers images on [/Speakers](https://in.pycon.org/2018/speakers.html) are not getting loaded.
It is because they are still pointing to the sample image. These can be fixed by just talking the image URLs from the Home page.

**Comment by ananyo2012** [comment]
Ah you are right. Need to update with the actual images. Can you add them @realslimshanky ?

**Comment by realslimshanky** [comment]
@ananyo2012 I'm working on it. Will take a couple of minuted more for the PR.
