### ISSUE TITLE
couldn't see social icons in speakers page

### ISSUE THREAD

**Issue by poornagurram** [pythonindia/inpycon2018#199]
<img width="1224" alt="screen shot 2018-09-19 at 12 39 18 pm" src="https://user-images.githubusercontent.com/9065157/45736632-27027480-bc09-11e8-9ab2-3ce4bc58f83c.png">

**Comment by realslimshanky** [comment]
@poornagurram would you like to help us out by sending a pull request?

**Comment by ananyo2012** [comment]
Sorry this was caused as I removed the font awesome link from header and updated with a different version. Don't worry I will take care of this.
