### ISSUE TITLE
A better design for mentioning previous PyCons.

### ISSUE THREAD

**Issue by Pulkit07** [pythonindia/inpycon2018#2]
The Idea of mentioning about Past PyCons is nice. In that section
let's have two rows with five pictures in each row. Each picture is
from one of the previous PyCons and is also a link to that PyCon description or
website.

**Comment by vnbang2003** [comment]
Mentioning of previous years has to done just by link in website years links only.We can actually skip this if required.
We should be speaking more about this year stuff more.
