### ISSUE TITLE
Provide a favicon

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2018#20]
A favicon is missing. I think the python logo in the middle of the banner logo can be used as the favicon.

**Comment by DollarAkshay** [comment]
I suggest using an online favicon generator like https://www.favicon-generator.org/
as it covers all possible cases and also provides a theme color for the entire website

**Comment by DollarAkshay** [comment]
I can do it if you provide me an SVG version of the logo

**Comment by webchirpy** [comment]
Added the app icons and favicons

**Comment by SaptakS** [comment]
Resolved. Closing.
