### ISSUE TITLE
Adjust sponsor dimensions for mobile screen view

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#207]
The sponsor logos have different sizes for smaller screen widths. We need to apply proper dimensions for the logos using media queries

**Comment by vipulgupta2048** [comment]
I am willing to take it up and learn more about the responsive element. Never actually got to that part of CSS. Do suggest things that I need to search for. 
I probably would refer https://www.w3schools.com/css/css_rwd_mediaqueries.asp

**Comment by ananyo2012** [comment]
Sure go ahead.Assigned it to you.
