### ISSUE TITLE
The event venue's height doesn't matches with the map height.

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon2018#21]
The map height appears more than the event venue's height in some browsers like chrome.

**Comment by DollarAkshay** [comment]
I noticed this too. Also why is its parent not as big as the child divs ? Its just there at the top with 0 height and some padding. 
![pycon india website 2](https://user-images.githubusercontent.com/6565924/34431918-ef1232ee-ec98-11e7-8ea7-2a32e8aa25c9.png)

**Comment by webchirpy** [comment]
Fixed the layout issue.

**Comment by SaptakS** [comment]
Resolved. Closing.
