### ISSUE TITLE
Add a page for workshop prerequisites and description

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#213]
This page is to facilitate participants to do the necessary setup for the workshops so they can cut down the time for doing the initial setup for the respective workshops. Most of the workshops have them in their proposal except the keynote workshops and sponsored ones that didn't come up from CFP. We need to properly organise and add content to the page

**Comment by ananyo2012** [comment]
**Jupyter hub and Binder by Carol Wiling**

Workshop Details:

We'll take an in-depth look at JupyterLab and its use for data science and scientific computing. We'll look at the new user interface functionality available to users of JupyterLab. Later, we will move beyond an individual's workflow with JupyterLab and see how JupyterHub brings JupyterLab to groups of users. We'll wrap up with a discussion of Binder and its ability to provide ephemeral computing environments for Jupyter notebooks and beyond.

**Comment by ananyo2012** [comment]
**Programming a Quantum Computer using Cirq by Vamsi Krishna Devabathini (Google)**

**Abstract:** This intermediate level workshop will focus on introduction to quantum computing and Cirq, python framework for creating quantum programming. It also includes a hands on tutorials implementing simple quantum algorithm(s) using Cirq.

**Prerequisites:** Basic knowledge of Python. Knowledge of Quantum computing is a plus but not required.

**Comment by ananyo2012** [comment]
**Understanding NLP - What's the feeling ? By Lakshya Sivaramakrishnan (Google)**

**Abstract:** This intermediate level talk would cover the basics required for natural language processing using NLTK in Python. We would then see it working in action through a sentiment analysis use-case.

**Pre-requisites:** Basic knowledge of Python

**Comment by realslimshanky** [comment]
@ananyo2012 on it.
