### ISSUE TITLE
Sponsor information missing

### ISSUE THREAD

**Issue by Gouravchawla** [pythonindia/inpycon2018#215]
Look at the screenshot below.
Missing information for sponsors: DBS, Elucidata and JetBrains.
 
![image](https://user-images.githubusercontent.com/2922351/46412406-1e975700-c73c-11e8-92eb-c52417723433.png)

**Comment by realslimshanky** [comment]
@ananyo2012 can you please provide information for these sponsors so they can be sorted?

**Comment by vipulgupta2048** [comment]
Didn't catch Elucidata, thanks for making the issue @Gouravchawla 
One might also look at this pending issue of some relevance - https://github.com/pythonindia/inpycon-blog/issues/179#issuecomment-426602062

**Comment by ananyo2012** [comment]
Added all sponsor information that were missing.
