### ISSUE TITLE
Improve the design of FAQ page.

### ISSUE THREAD

**Issue by Pulkit07** [pythonindia/inpycon2018#27]
Right now at FAQ page, the left alignment of answer is not the same as that of question which seems a bit awkward. I think we can do better here.

**Comment by realslimshanky** [comment]
It would look cleaner this way. I guess we should create an issue regarding this.

**Comment by ananyo2012** [comment]
Yup we should make a new issue for this. Should we close this as the FAQ page looks good with the indentation of Question and Answers as per me ?

**Comment by realslimshanky** [comment]
Sure. Let's close this and shift conversation regarding this issue to #51

**Comment by ananyo2012** [comment]
The present design is ok and preferred by everyone. So this can be closed now.
