### ISSUE TITLE
Add disqus for FAQs

### ISSUE THREAD

**Issue by Pulkit07** [pythonindia/inpycon2018#29]
There have been generally a lot of questions arising related to difference and intersections of conference, workshops and devsprints. Let's add them and have a FAQ which can be a good go-to place for any doubt for any pythonista who wants to come to PyCon India 2018.

**Comment by ananyo2012** [comment]
@chirag200666 @realslimshanky We should add Disqus for adding comments directly in the FAQ page. What do you say ?

**Comment by realslimshanky** [comment]
Disqus also brings a lot of other dependencies with it like google analytics and other js which we might not be ready to include. We need to Disqus this further. Other options which I would suggest.

- Adding only those questions which are frequently asked on `contact@in.pycon.org` to FAQ
- Adding a custom made comment feature as an alternative to Disqus.

cc: @ananyo2012 @chirag200666

**Comment by ananyo2012** [comment]
@realslimshanky Custom made comment feature sounds good to me. But we would need a backend for that. This is a static website originally. We need to move it to a backend framework like Flask or Django.

**Comment by realslimshanky** [comment]
@ananyo2012 true that. So, we have Disqus and questions from `contact@in.pycon.org`. Any other way you can think of?

**Comment by ananyo2012** [comment]
Updating questions every time from `contact@in.pycon.org` can be tough. Disqus can help visitors to see the questions that are being asked there directly.

**Comment by ananyo2012** [comment]
Good idea. Can you check the faq html elements and add that code in a
snippet in readme?

**Comment by JoyBhalla** [comment]
Will do,tonight or by tomorrow

**Comment by realslimshanky** [comment]
@JoyBhalla any updates on this issue?

**Comment by realslimshanky** [comment]
@JoyBhalla no worries. Ping here when you are done.

**Comment by JoyBhalla** [comment]
@ananyo2012 can you please specify what the html elements are i'm a little confused.

**Comment by ananyo2012** [comment]
```
<div class="pycon-faq">
          <h5><b>Q. Where can I find updates related to PyCon India 2018?</b></h5>
          <ul class="faq-answer">
              <li> All the communications related to conference happens on PyCon India mailing list. You can receive the updates by
                     joining <a href="https://mail.python.org/mailman/listinfo/inpycon">InPyCon mailing list</a> or you can ping us on
                     <a href="https://webchat.freenode.net/?channels=%23pyconindia">#pyconindia</a> IRC channel on freenode server.
              </li>
          </ul>
        </div>
```

I was referring to this block @JoyBhalla

**Comment by vipulgupta2048** [comment]
@ananyo2012 Should we close this now?

**Comment by ananyo2012** [comment]
I am keeping it open for the discord discussion. Should I make a specific issue for that ? Also some more FAQs need to be added.

**Comment by realslimshanky** [comment]
@ananyo2012 we can always edit the issue title and description to our needs which is always better than creating a new issue.

**Comment by ananyo2012** [comment]
Yeah that is good I guess

**Comment by Ayukha** [comment]
Can I take this up?

**Comment by realslimshanky** [comment]
@Ayukha sure. Please go ahead and raise a PR with the requested feature. I'm assigning this issue to you.

**Comment by ananyo2012** [comment]
Discusses with team and everyone didn't approve of it. Hence closing this.
