### ISSUE TITLE
Pycon India 2017 wrong location

### ISSUE THREAD

**Issue by juggernaut451** [pythonindia/inpycon2018#39]
In the journey of Pycon India section, the location of 2017 event is given as `Indian Institute of Science, Bangalore` but the actual event took place at `Shaheed Sukhdev College
Of Business Studies `

**Comment by realslimshanky** [comment]
@juggernaut451 please also share the link/screenshot where it is so.

**Comment by bhansa** [comment]
I think we can refer [pycon 2017](https://in.pycon.org/2017/) website for this @realslimshanky.

**Comment by realslimshanky** [comment]
@bhansa I guess that's what @juggernaut451 used to fix the issue in #40
