### ISSUE TITLE
Link for submitting a proposal

### ISSUE THREAD

**Issue by akshitac8** [pythonindia/inpycon2018#41]
I was not able to find a link while hovering at ***here***.

![screenshot from 2018-03-28 23-17-50](https://user-images.githubusercontent.com/21353757/38047114-1cad6a52-32df-11e8-847d-21933544413a.png)

**Comment by realslimshanky** [comment]
@akshitac8 CFP is still not open yet and the URL will be added to `here` when it will. Until then we should notify the same on FAQ as well. Thanks for raising the issue. I'm sure someone would take up the task and create a PR soon.

**Comment by akshitac8** [comment]
Ohkay @realslimshanky  That's great :slightly_smiling_face:

**Comment by ananyo2012** [comment]
@akshitac8 You can take up this PR in the mean time we are working on the CFP. Just add this text `Link for submitting Proposal will be added soon.`

**Comment by akshitac8** [comment]
Ohkay @ananyo2012  I will add the changes :slightly_smiling_face:

**Comment by akshitac8** [comment]
Hello, @ananyo2012  I wanted to ask about the changes as they are not displayed on the site. Are the changes not correct ??

**Comment by ananyo2012** [comment]
Hi @akshitac8 , the changes have been deployed now. They are live in the website.
