### ISSUE TITLE
Update in Venue & date required on the website.

### ISSUE THREAD

**Issue by chirag200666** [pythonindia/inpycon2018#42]
Following changes are required on the website:

- The new Venue for the conference will be HICC, Hyderabad
- The dates of the PyCon India 2018 will be 5th - 9th October 2018.

**Comment by inovizz** [comment]
@chirag200666 The info you provided on this issue is final? Or do we need to seek confirmation on HICC for the conference venue?

**Comment by chirag200666** [comment]
Hi @inovizz 
The venue is available and we are in the process of blocking it.

**Comment by realslimshanky** [comment]
We can close this issue now as it has been resolved in #43.

**Comment by chirag200666** [comment]
@realslimshanky 
This change needs to go live, so we can close the issue. Do you have info on how to do the same?

**Comment by realslimshanky** [comment]
@chirag200666 one needs to access the server and pull changes from GitHub.

**Comment by akshitac8** [comment]
Hi @chirag200666 I think the same changes are also needed at [FAQ](https://in.pycon.org/2018/faq.html) page.
Can I propose a PR with the changes?

**Comment by realslimshanky** [comment]
@akshitac8 please go ahead and raise the PR.

**Comment by akshitac8** [comment]
ohkay @chirag200666 
The timings mentioned at [FAQ](https://in.pycon.org/2018/faq.html) page will remain the same?

**Comment by inovizz** [comment]
@akshitac8 - It may defer, allow us some time to come back with exact timings.

**Comment by realslimshanky** [comment]
@akshitac8 please subscribe to [PyCon India mailing list](https://mail.python.org/mailman/listinfo/inpycon) so you receive all the updates as they happen.

**Comment by akshitac8** [comment]
Ohkay @inovizz, for now, I will keep the same timing and @realslimshanky I have already subscribed to the list. :slightly_smiling_face:

**Comment by akshitac8** [comment]
I have made the required changes.
Kindly review the changes :slightly_smiling_face:

**Comment by ananyo2012** [comment]
Hi @akshitac8 I will review the changes shortly. Thanks for your contribution.

**Comment by ananyo2012** [comment]
Closing this as all issues regarding date and location have been resolved. Please make a new issue if any more issues are noticed.
