### ISSUE TITLE
Journey section content

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/inpycon2018#6]
We need to come up with better content in journey section.
Presently we are just showing 1) Dates (2) Venue (3) City .

@SaptakS @aavrug @sayanchowdhury @ciypro @DollarAkshay : Please do share thought on it

**Comment by vnbang2003** [comment]
@SaptakS  Any update on this ?

**Comment by SaptakS** [comment]
@vnbang2003 I am waiting for the one-liner description. Apart from that, it is ready.

**Comment by vnbang2003** [comment]
@SaptakS Let's get photo's moving forward. We can update one-liner we are get

**Comment by SaptakS** [comment]
Okay. I will push the code.
