### ISSUE TITLE
Start ticket sales

### ISSUE THREAD

**Issue by chirag200666** [pythonindia/inpycon2018#61]
The ticket sales should start as soon as possible.

@ananyo2012 
Some of the code has been commented for ticket pricing options & buy button, can you please explore if can use that and coordinate with Gokul to make it live.

**Comment by ananyo2012** [comment]
For the time being I am adding the link with a modal opening on click.

**Comment by ananyo2012** [comment]
Tickets live at https://in.explara.com/e/pycon-india-2018 . Update it in the website
