### ISSUE TITLE
Hover Effect on Social Media Icons.

### ISSUE THREAD

**Issue by utkarsh2102** [pythonindia/inpycon2018#63]
It'd be great to add a hover effect on the social media icons. 
Their shade would get darker when hovered. 
Can I take up this task?

**Comment by realslimshanky** [comment]
@utkarsh2102 please do. ping here with the PR or if you have any issue. thanks :)

**Comment by utkarsh2102** [comment]
Sure @realslimshanky.
I'd submit the PR on 16th April, positively.

**Comment by utkarsh2102** [comment]
@realslimshanky.
Please refer to PR #64 for this issue.

**Comment by ananyo2012** [comment]
Thanks for your contribution @utkarsh2102 . Resolved in #64 .
