### ISSUE TITLE
[Urgent] Update/Delete all unused media

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2018#68]
Due to recent changes in the venue, I think some of the media in the /icons and /img folder have become redundant. As it was either used for the conference being held in Bangalore or as dummy content. Favicons for the website need to be updated too if not done already.

**Comment by tushar-nitave** [comment]
Are you taking up the task?

**Comment by ananyo2012** [comment]
Yeah the favicons of different dimensions have to be updated. We have the
updated psd of the logo. This is a design task though. If anyone is
interested in taking up the task I can share the psd or else we have to
reach out @webchirpy for this.

**Comment by realslimshanky** [comment]
Please go ahead @parthsharma2 and create a PR.
