### ISSUE TITLE
Redesign CFP and tickets buttons

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2018#70]
As [suggested](https://github.com/pythonindia/inpycon2018/issues/62#issuecomment-382365517) by @rajataaron, CFP and Tickets buttons can be redesigned for a clear visibility. He also gave a sample.
![image](https://user-images.githubusercontent.com/10004530/38936574-b5662a62-433e-11e8-9a6e-2f930bc7ac8e.png)

**Comment by ananyo2012** [comment]
The current ticket button present look like this (The code is commented out now)
![screenshot from 2018-04-18 22-16-52](https://user-images.githubusercontent.com/10486343/38946243-7d9e6244-4356-11e8-829d-33276c43d368.png)
Though @rajataaron's design looks good as well!

**Comment by rajataaron** [comment]
@ananyo2012  if it is already done then it is ok and this looks nice and clean too. :+1:

**Comment by ananyo2012** [comment]
Yeah most of the code is ready. It's just commented out
ᐧ

**Comment by ananyo2012** [comment]
Solved in #67
