### ISSUE TITLE
Mobile website overflowing.

### ISSUE THREAD

**Issue by DollarAkshay** [pythonindia/inpycon2018#8]
A lot of elements are overflowing when viewed at 320px width on chrome, causing a weird gap on the right

**Comment by webchirpy** [comment]
Could you please check now as we have fixed the issue?

**Comment by DollarAkshay** [comment]
One last thing, the Logo at the footer is overflowing. Everything else looks fine.

**Comment by DollarAkshay** [comment]
There seems to be a gap on the right even on medium-small desktop devices 

![pycon india website](https://user-images.githubusercontent.com/6565924/34431483-9eba62ce-ec95-11e7-8b46-a408d86b53b8.png)

**Comment by ananyo2012** [comment]
Closing this as this looks to be fixed. Open if it is reproduced again.
