### ISSUE TITLE
Suggested updates in FAQs

### ISSUE THREAD

**Issue by chirag200666** [pythonindia/inpycon2018#80]
Hi @pythonindia/pycon-2018-team 
Below are some of the changes I think will be good to update on the FAQ page of the website: 
1. Q. Where can I find updates related to PyCon India 2018?
We can remove the IRC channel & put twitter there. 

2. Q. I want to present a talk/workshop at the conference. What should I do?
We can add the link to the CFP page now.

4. Q. I want to volunteer for the conference. What should I do?
I think we can point it to the email/blog post with the form for volunteer registration.

9. Q. Where can I stay while in Hyderabad for the conference?
I think we can mention we will be listing down some recommended hotels near the venue, possibly with discounts.

**Comment by vipulgupta2048** [comment]
I totally agree with point 1, I think Twitter will be the best for updates and the mailing list too. 
For question 4, I think a blog post similar to this could be made - https://in.pycon.org/blog/2017/travel-and-hotel-2017.html

**Comment by ananyo2012** [comment]
We can probably add the link for the volunteer page in Q3. For Q4 I was thinking if we can put a dedicated page similar to https://us.pycon.org/2018/venue/ . People often don't go through all blog posts. We should have a dedicated page for Travel and Accommodation help.

**Comment by dixitchopra** [comment]
I can tak this up.

**Comment by ananyo2012** [comment]
I am taking this up. This is a priority issue.
