### ISSUE TITLE
Pycon hyderabad 2018 logo showing up in older blog posts

### ISSUE THREAD

**Issue by bhansa** [pythonindia/inpycon2018#82]
I see that even blog posts from 2017 have PyCon Hyderabad 2018 logo, at both header and footer.
Is this expected?  

![image](https://user-images.githubusercontent.com/9723884/39981581-c8a37af0-576e-11e8-9e26-5879f3e0d040.png)

**Comment by vipulgupta2048** [comment]
Hi @bhansa, since the blog site being a single page website, then this kind of behavior that you reported looks normal to me. Scroll down the logo ain't going anywhere even if you reach PyCon India 2016 Blog posts.

**Comment by ananyo2012** [comment]
Yeah @vipulgupta2048 is correct. Every year the design of the blog is changes w.r.t to the theme of the website.

**Comment by bhansa** [comment]
I think we can close this issue, if its expected @vipulgupta2048 @ananyo2012
