### ISSUE TITLE
Background heading is not rendered correctly in mobile

### ISSUE THREAD

**Issue by vkmrishad** [pythonindia/inpycon2018#83]
Hi,
I have noticed an issue. Background header is not rendered correctly in mobile.
Please remove from mobile or optimize heading according to screen resolution.

![screen shot 2018-05-15 at 10 22 43 pm](https://user-images.githubusercontent.com/18536460/40071781-6abf4e24-588f-11e8-9710-bd3f74903f14.png)

**Comment by realslimshanky** [comment]
@vkmrishad thanks for creating the issue. Would you like to help to fix this as well?

**Comment by bhansa** [comment]
@vkmrishad are you working on this issue?

**Comment by vkmrishad** [comment]
Hi @bhansa,
I am not working on this issue.

**Comment by ananyo2012** [comment]
I would suggest removing the background text for mobile views.

**Comment by vipulgupta2048** [comment]
@bhansa  Would like to take this up? then go ahead with it, make a pull request for the same.
