### ISSUE TITLE
Journey of Pycon India 2009 / 2012 content changes:

### ISSUE THREAD

**Issue by felsen** [pythonindia/inpycon2018#84]
PyCon 2009 and PyCon 2012 short description looks same.

![image](https://user-images.githubusercontent.com/7158481/40179147-318a9230-5a01-11e8-9484-7b4f1b5e300b.png)

**Comment by HarendraSingh22** [comment]
Oh ! This is a blunder 😂.

@ananyo2012 tag someone who was at that Pycon and request him/her to write something about it.

**Comment by vipulgupta2048** [comment]
Well, @nibrahim I think you could enlighten us on the same. As to how PyCon India 2009 and 2012 were.

**Comment by ananyo2012** [comment]
I just read through the content for each year. The tagline is same for years 2009-12 and same for year onwards. The only mistake is the text "first" should be made "fourth"

**Comment by ananyo2012** [comment]
Fixed in #93
