### ISSUE TITLE
[Feature] Share bar ribbon

### ISSUE THREAD

**Issue by bhansa** [pythonindia/inpycon2018#86]
We should have a share bar ribbon, as we have share bar on [PyCon 2017](https://in.pycon.org/2017/) website. It gives ease for people to share the event details on social media.

Please share your thoughts about the design, placement etc.

**Comment by vipulgupta2048** [comment]
That's a good idea, can you share us a screenshot of what you are trying to accomplish and if you like to take up this task?

**Comment by bhansa** [comment]
Sure @vipulgupta2048, I'll own this one and will share the implementation later today.

**Comment by realslimshanky** [comment]
@bhansa any update on this issue?
