### ISSUE TITLE
The timeline buttons are not needed in full screen

### ISSUE THREAD

**Issue by GauravJain98** [pythonindia/inpycon2018#88]
![screenshot-2018-5-19 pycon india 2018 in hyderabad october 5th to 9th](https://user-images.githubusercontent.com/19913130/40266576-87b135b8-5b6b-11e8-9fbd-edf8e7d195a7.png)
the arrow buttons should be hidden in full screen

**Comment by GauravJain98** [comment]
When I opened it on my desktop I thought it was a bug (them not functioning)and realised it purpose on a smaller screen

**Comment by GauravJain98** [comment]
We can have a 
if(window.outerWidth > screensize){
Buttons disabled
}

**Comment by ananyo2012** [comment]
Yeah we should remove the arrows for large and medium screen dimensions. Its only required for smaller screen widths.

**Comment by vipulgupta2048** [comment]
@GauravJain98  Any updates on the issue or please notify if you are working on it ?

**Comment by ananyo2012** [comment]
I guess this is open to take up since its already been over an week.

**Comment by a2un** [comment]
Okay taking it up!

**Comment by a2un** [comment]
Hi could you confirm if the issue is open.

**Comment by a2un** [comment]
I think the arrow is appearing because there is an extra space _before_ the 2009. we update the timeline without a lot space the arrow should go

**Comment by ananyo2012** [comment]
Hi Arun,
In case you figured out a solution can you submit a PR ?

**Comment by a2un** [comment]
Sure. I am checking and working on it.

**Comment by a2un** [comment]
updated the PR #113 with this commit.

**Comment by ananyo2012** [comment]
@a2un Are you working on this ?

**Comment by samuellawrentz** [comment]
Hi,
I would like to contribute. Is someone working on it? 
Couldn't this be done with CSS using media queries? That is, make the buttons visible only for mobile and tabs. It could be fairly simple and efficient.
```
@media screen and (max-width:768px){
        .cd-timeline-navigation a.prev {
               display:block
           }
}
```

**Comment by vipulgupta2048** [comment]
@samuellawrentz Sure, go for it. Make a pull request.

**Comment by samuellawrentz** [comment]
I have made a PR. Please review it.
