### ISSUE TITLE
Add Keynote speakers to the website

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#90]

**Comment by rajataaron** [comment]
Is anybody doing this?

**Comment by vipulgupta2048** [comment]
@rajataaron Looks like @ananyo2012 has assigned himself to the issue, hence he would surely be solving it in a few days.

**Comment by ananyo2012** [comment]
Yeah I am on it. The code is already there. Just need little tweaks and resizing the images.

**Comment by vipulgupta2048** [comment]
Fixed #90 in #96
