### ISSUE TITLE
Add a venue page describing the venue

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon2018#91]
This should be some what similar to https://us.pycon.org/2018/venue/ . Approach the local volunteers for details regarding the venue for accommodation details etc. You can contact them in discord channel.

**Comment by vipulgupta2048** [comment]
@ananyo2012 I would suggest letting someone from the local community of HydPy to take this up, there will be a ton of fine details that need to be mentioned. I highly recommend if the person assigned is from Hyderabad only.

**Comment by ananyo2012** [comment]
Yeah sure I will fill in the details from a localite only. Then create a
doc with the details.

**Comment by ananyo2012** [comment]
Yes we discussed about it. I will taking help from from the HydPy team in
this and adding the content.

**Comment by realslimshanky** [comment]
@ananyo2012 any update on this issue?

**Comment by ananyo2012** [comment]
Yeah I am still in the process of compiling the doc. Will send out the link
to the doc once it is done.

**Comment by realslimshanky** [comment]
@ananyo2012 any update on the issue?
We can also reach out to the inpycon mailing list with a draft.

**Comment by ananyo2012** [comment]
So we need 2 pages to be created here - Travelling to Hyderabad, Accomodation. First one can be created immediately.

Content for `Travelling to Hyderabad`  should contain Travel information by all 3 modes - Air, Train and Road.

**Comment by aswanipranjal** [comment]
@ananyo2012 @realslimshanky @vipulgupta2048 is there any specific information/document that we have to refer to create these pages? If there is not, should we first gather information and create a doc?

**Comment by realslimshanky** [comment]
@aswanipranjal internet is your friend here.

**Comment by vipulgupta2048** [comment]
Adding on to that, you can refer to this [PyCon India 2017 Blog](https://in.pycon.org/blog/2017/travel-and-hotel-2017.html) for more information on how to go on about format.

**Comment by aswanipranjal** [comment]
https://docs.google.com/document/d/16EVCLID2buQD8R5odGxz_qc8gHiNQ-Cdx8X4Zi_bPpY/edit?usp=sharing

@ananyo2012 @realslimshanky @vipulgupta2048 

Sorry about the delay.

**Comment by realslimshanky** [comment]
@aswanipranjal can you please create a Pull Request as well with the content in the doc? It'll be easier to review and can be merged in one go. Use the same template as [Volunteer](https://in.pycon.org/2018/volunteer.html)

**Comment by ananyo2012** [comment]
@aswanipranjal I have commented on the doc. The information you collected is mostly for Travelling to Venue within Hyderabad. You should also add the information to how to reach Hyderabad from a different city via Air, Rail or Road. Like which Station they should reach, which Highway to take in case Travelling via personal Transport etc.

**Comment by ananyo2012** [comment]
Ah It actually has lot of information. You can add the link at the end. But
you must add the Travel information separately in the page.
ᐧ

**Comment by aswanipranjal** [comment]
@ananyo2012 @vipulgupta2048 @realslimshanky does this has to be a page (such as volunteer, sponsors, coc) or will this be a blog post?

**Comment by ananyo2012** [comment]
It will be  a separate page in the website. I already mentioned that in the
issue.

**Comment by vipulgupta2048** [comment]
@aswanipranjal This will be a page, yes. 
Also, to save some time you can mention @pythonindia/pycon-2018-team to get more views from the team members
