### ISSUE TITLE
[Analytics] Tag management for this website

### ISSUE THREAD

**Issue by bhansa** [pythonindia/inpycon2018#94]
I see that we are using GTM for tagging here, It will be very important to get at least the analytics of the page and doing the tagging right way.
Events which will be important later like, no. of click on "Buy tickets" CTA or how many people are getting redirected successfully to other links and the ticket website.

Let me know what is the approach for this.

**Comment by ananyo2012** [comment]
Should we use url shorteners for this?

**Comment by bhansa** [comment]
Not sure about how much data does URL shorteners give, since gtag is already in place for a long time and we should have captured previous data as well (need to check with @chirag200666 ).

Also, I think URL shorteners can be used for links shared on the web but not sure if we can use the same for the website (internal or external links) as well, plus gtag will give the flexibility to update dataLayer on certain events on the page. 
It will also help us later to track our blog posts etc.

**Comment by ananyo2012** [comment]
@bhansa Sorry I didn't get time to focus on analytics. I will be initiating the discussion on mailing list coming week and start the work on analytics soon.

**Comment by ananyo2012** [comment]
Emailed Vijay and Satyakam today. Waiting for the reply.

**Comment by bhansa** [comment]
Any update on the Analytics dashboard access @ananyo2012 @chirag200666

**Comment by ananyo2012** [comment]
Not yet. @chirag200666 Probably got the access. Need to talk to him.

**Comment by ananyo2012** [comment]
Need to talk on Webchirpy on this.

**Comment by bhansa** [comment]
I'm closing this issue.
